### ISSUE TITLE
Issue with Yarn package `@armada-inc/gatsby-plugin-amp`

### ISSUE THREAD

**Issue by arthurgeek** [draftbox-co/gatsby-ghost-balsa-theme#10]
When installing dependencies with `yarn install`, it downloads this package: https://yarnpkg.com/package/@armada-inc/gatsby-plugin-amp.

This package Github repo points to: https://github.com/armada-inc/gatsby-plugin-amp.

The issue: [the package files](https://yarnpkg.com/package/@armada-inc/gatsby-plugin-amp?files) do not correspond to the [source code](https://github.com/armada-inc/gatsby-plugin-amp).

**Comment by thandaanda** [comment]
Hi @arthurgeek ,

Thanks for pointing out the issue. We will update the said plugin in the next iteration.

**Comment by thandaanda** [comment]
Hi @arthurgeek,

We have released the new version of theme with updated dependency and updated source code.

**Comment by arthurgeek** [comment]
There's no version `0.2.4` published here: https://yarnpkg.com/package/@armada-inc/gatsby-plugin-amp

**Comment by arthurgeek** [comment]
Oh, my bad. I see it moved to: https://yarnpkg.com/package/@draftbox-co/gatsby-plugin-amp.
